### ISSUE TITLE
Doesn't need to initialize API keys that way

### ISSUE THREAD

**Issue by ErvalhouS** [AyuntamientoPuertoReal/participacion-ciudadana#30]
https://github.com/AyuntamientoPuertoReal/participacion-ciudadana/blob/b89c553258af1ffb19837b8a414d2f1f88d7149d/app/controllers/api_controller.rb#L5

Those lines should be only executed in case you need to create a new API key. This makes more sense in the seeds file.

**Comment by AlejandroVirlan** [comment]
Thank you. I have fixed it #31.
